apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcsh-rcon-console
  labels:
    app: mcsh-rcon-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcsh-rcon-console
  template:
    metadata:
      labels:
        app: mcsh-rcon-console
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1001
      containers:
      - name: mcsh-rcon-console
        resources:
          limits:
            memory: 100Mi
            cpu: 100m
        securityContext:
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        image: harbor.internal/quantomworks/mcsh-rcon-console
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: rcon-config
          mountPath: /var/www/html/config.php
          subPath: config.php
          readOnly: true
      volumes:
      - name: rcon-config
        configMap:
          name: rcon-config